import type { dataProductsType } from './dataCard.types.ts';

export const dataProducts: dataProductsType[] = [
  {
    id: 1,
    photo: 'https://avatarko.ru/img/kartinka/1/Crazy_Frog.jpg',
    name: 'Моторное масло dfd sf ds f dsf sdf asdf asd f sde d sf dsМоторное масло dfd sf ds f dsf sdf asdf asd f sde d sf dsМоторное масло dfd sf ds f dsf sdf asdf asd f sde d sf dsМоторное масло dfd sf ds f dsf sdf asdf asd f sde d sf ds',
    price: 89.8,
    currency: 'BYN',
    currencyExchangeRate: 3,
    VIN: 'WBAPD52040WC92486',
    year: 2006,
    article: '2221093',
    model: 'Ford Focus',
  },
  {
    id: 2,
    photo: '',
    name: 'Моторное масло',
    price: 89.8,
    currency: 'BYN',
    currencyExchangeRate: 3,
    VIN: 'WBAPD52040WC92486',
    year: 2006,
    article: '2221093',
    model: 'Ford Focus',
  },
  {
    id: 3,
    photo: '',
    name: 'Моторное масло',
    price: 89.8,
    currency: 'BYN',
    currencyExchangeRate: 3,
    VIN: 'WBAPD52040WC92486',
    year: 2006,
    article: '2221093',
    model: 'Ford Focus',
  },
  {
    id: 4,
    photo: '',
    name: 'Моторное масло',
    price: 89.8,
    currency: 'BYN',
    currencyExchangeRate: 3,
    VIN: 'WBAPD52040WC92486',
    year: 2006,
    article: '2221093',
    model: 'Ford Focus',
  },
  {
    id: 5,
    photo: '',
    name: 'Моторное масло',
    price: 89.8,
    currency: 'BYN',
    currencyExchangeRate: 3,
    VIN: 'WBAPD52040WC92486',
    year: 2006,
    article: '2221093',
    model: 'Ford Focus',
  },
  {
    id: 6,
    photo: '',
    name: 'Моторное масло',
    price: 89.8,
    currency: 'BYN',
    currencyExchangeRate: 3,
    VIN: 'WBAPD52040WC92486',
    year: 2006,
    article: '2221093',
    model: 'Ford Focus',
  },
  {
    id: 7,
    photo: '',
    name: 'Моторное масло',
    price: 89.8,
    currency: 'BYN',
    currencyExchangeRate: 3,
    VIN: 'WBAPD52040WC92486',
    year: 2006,
    article: '2221093',
    model: 'Ford Focus',
  },
  {
    id: 8,
    photo: '',
    name: 'Моторное масло',
    price: 89.8,
    currency: 'BYN',
    currencyExchangeRate: 3,
    VIN: 'WBAPD52040WC92486',
    year: 2006,
    article: '2221093',
    model: 'Ford Focus',
  },
  {
    id: 9,
    photo: '',
    name: 'Моторное масло',
    price: 89.8,
    currency: 'BYN',
    currencyExchangeRate: 3,
    VIN: 'WBAPD52040WC92486',
    year: 2006,
    article: '2221093',
    model: 'Ford Focus',
  },
  {
    id: 10,
    photo: '',
    name: 'Моторное масло',
    price: 89.8,
    currency: 'BYN',
    currencyExchangeRate: 3,
    VIN: 'WBAPD52040WC92486',
    year: 2006,
    article: '2221093',
    model: 'Ford Focus',
  },
];
